# Generated by Django 2.2.5 on 2019-10-16 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Professor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcentrationArea',
            fields=[
                ('concentration_area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'concentration_areas',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword_id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('start_submit', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(default='will_open', max_length=30)),
                ('concentration_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.ConcentrationArea')),
                ('keywords', models.ManyToManyField(to='Events.Keyword')),
                ('reviews', models.ManyToManyField(to='Professor.Professor')),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
