# Generated by Django 2.2.5 on 2019-10-13 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_events_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='startSubmit',
            new_name='start_submit',
        ),
    ]
