# Generated by Django 2.2.5 on 2019-10-13 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Events', '0001_initial'),
        ('Administrador', '0001_initial'),
        ('Professor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('tittle', models.CharField(max_length=30)),
                ('summary', models.TextField()),
                ('readercritic', models.CharField(max_length=30)),
                ('status', models.CharField(default='waiting_revision', max_length=30)),
                ('authors', models.ManyToManyField(to='Artigos.Author')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.Events')),
                ('proofreader', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisor', to='Professor.Professor')),
                ('user_submit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_submit', to='Administrador.User')),
            ],
            options={
                'db_table': 'articles',
            },
        ),
    ]
