# Generated by Django 2.2.5 on 2019-10-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artigos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
