# Generated by Django 2.2.5 on 2019-10-15 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artigos', '0002_article_article_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='proofreader',
            new_name='reviewer',
        ),
    ]
