# Generated by Django 2.2.5 on 2019-10-15 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artigos', '0003_auto_20191015_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='readercritic',
        ),
    ]
